package maidul.care.com.myapplication.utility;

import android.content.Context;
import android.content.SharedPreferences;

/**
 * Created by maidulislam on 25/01/2017.
 */
public class Constants {
    public static final String ARG_PLANET_NUMBER = "planet_number";

    public static final String DATA_OVERVIEW_FL1 = "[{\"Id\":1,\"image\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\"},{\"Id\":2,\"image\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model3.png\"},{\"Id\":3,\"image\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model3.png\"}]";
    public static final String DATA_OVERVIEW_FL2 = "[{\"Id\":1,\"text\":\"NAUSS international activities aim to gather knowledge and experience from all around the world in cooperation.\"},{\"Id\":2,\"text\":\"NAUSS specializes in advanced security related studies at postgraduate level in the form of diplomas, master’s degrees and doctorate.\"},{\"Id\":3,\"text\":\"NAUSS international activities aim to gather knowledge and experience from all around the world in cooperation.\"},{\"Id\":4,\"text\":\"NAUSS has attended over 700 international conferences discussing and facing all types of security related issues.\"},{\"Id\":2,\"text\":\"NAUSS is the only academic institution directly serving the Council of Arab Interior Ministers.\"},{\"Id\":3,\"text\":\"Programs at NAUSS are offered in accordance with the directions and advice of the Council of Arab Interior Ministers and the Arab League.\"}]";

    public static final String DATA_OVERVIEW_FL3 = "[{\"Id\":1,\"image\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_21122016.png\",\"text\":\"Academic Program on The Use of Color Printers in Forgery Crimes\",\"text1\":\"08-January-2017 :\",\"text2\":\"Attendees included personnel from investigative commissions, judicial bodies, and financial establishments and banks from different Arab countries.\"},{\"Id\":2,\"image\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_05012017.png\",\"text\":\"UN Organizations Praise the Efforts of NAUSS in Facing Crises and Disasters\",\"text1\":\"05-January-2017 :\",\"text2\":\"In cooperation with the International Civil Defence Organization (ICDO), the Crisis Center and Leadership Development at the University organized and held this eve…\"},{\"Id\":3,\"image\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_27122016_3.jpg\",\"text\":\"Symposium: Strengthening the Role of Sports Clubs and Cultural Associations in Raising Awareness of the Dangers of Terrorism and Extremism\",\"text1\":\"27-December-2016 :\",\"text2\":\"This symposium is being attended by 112 officials from ministries of interior, media, culture, youth, and sports – as well as sports.\"},{\"Id\":4,\"image\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_08012017.png\",\"text\":\"Geneva Forum: Towards an Academic Methodology to Deal with Crises and Disasters\",\"text1\":\"22-December-2016 :\",\"text2\":\"NAUSS organized this important forum that took place in Geneva, Switzerland, from the 19th – 20th of December in cooperation with the International Civil\"}]";

    public static final String ARG_OVERVIEW_ABOUT = "{\"overview\":{\"about\":{\"normaltext\":[{\"text\":\"جامعة نايف العربية للعلوم الأمنية منظمة عربية ذات شخصية اعتبارية تتمتع بصفة دبلوماسية ومقرها مدينة الرياض (عاصمة المملكة العربية السعودية)، وهي الجهاز العلمي لمجلس وزراء الداخلية العرب، تعنى بالتعليم العالي والبحث العلمي والتدريب في المجالات الأمنية والميادين ذات العلاقة.\",},{\"text\":\"وقد بدأت نشاطها العلمي عام 1980م في إطار سعيها نحو تحقيق تكامل الجهود العربية الأمنية تحت مظلة جامعة الدول العربية؛ حتى برزت إلى حيز الوجود صرحًا عربيًّا علميًّا أمنيًّا يخدم جميع الأجهزة المرتبطة بوزارات الداخلية والشؤون الاجتماعية والعمل والعدل والمؤسسات المجتمعية في الدول العربية في سبيل وقاية المجتمع العربي مالجريمة والانحراف، منطلقة من منهج علمي جعلها في مصاف المؤسسات والجامعات العريقة، بل تنفرد بميدانها الأمني الذي تكرس فيه الجهود لينعم المجتمع العربي بالأمن والأمان والاطمئنان انطلاقًا من أن الأمن هو الركيزة الأساسية لحماية المكتسبات التنموية والحضارية وتحقيق النهضة الشاملة.\",},{\"text\":\"وتتمثل رؤية الجامعة في تحقيق الريادة في العلوم الأمنية والدراسات الاستراتيجية لبلوغ مستوى علمي متميز عربيًّا وعالميًّا.\",},{\"text\":\"وتقوم رسالة الجامعة على الارتقاء بالعلوم الأمنية فكرًا ومنهجًا بما يسهم في تطوير أداء أجهزة الأمن والعدالة الجنائية من منطلق المفهوم الشامل للأمن بهدي من الشريعة الإسلامية، ووضع الاستراتيجيات لاستشراف التحديات والمهددات الأمنية ومعالجتها بأسلوب علمي.\",},{\"text\":\"وترتبط الجامعة بمجلس وزراء الداخلية العرب، وقد حددت أهدافها بما يلي:\",}],\"listtext\":[{\"text\":\"تأصيل العلوم الأمنية والتعريف بأحكام التشريع الإسلامي.\",},{\"text\":\"إتاحة التخصصات العلمية في الدراسات العليا في ميادين الأمن بمفهومه الشامل لأبناء الدول العربية.\",},{\"text\":\"تدريب الكوادر الأمنية والمهنية العربية وتأهيلهم في مجال العدالة الجنائية ومكافحة الجريمة.\",},{\"text\":\"إثراء البحث العلمي في مجالات الدراسات الأمنية والاستراتيجية، وتقديم الاستشارات العلمية، ورفد المكتبة الأمنية بالأبحاث والدراسات المتخصصة.\",},{\"text\":\"تعزيز التعاون العلمي والأمني مع المؤسسات العلمية والشرطية والمنظمات الدولية.\",},{\"text\":\"الإسهام في تنمية الحس الأمني بما يخدم قضايا التنمية المستدامة. \",}]}}}";

    final public static String BaseUrl = "http://appdev1:8050/token";


    public static final int FLAG_DONT_SHOW_START_LOGS = 1;
    public static final int FLAG_DONT_SHOW_SUCCESS_LOGS = 2;
    public static final int FLAG_DONT_SHOW_FAILURE_LOGS = 4;
    public static final int FLAG_DONT_SHOW_FINISH_LOGS = 8;
    public static final int FLAG_SHOW_LOGS = 16;
    public static final int FLAG_SHOW_LOADER = 32;
    public static final int FLAG_DONT_STOP_LOADER = 64;

    public static final int ID_TOKEN = 1001;
    public static final int ID_LOGIN = 1002;
    public static final int ROW_COUNT = 10;
    public static final String CLASS_DETAILS = "sample.naif.com.nauss2.DetailsPage.ComplainDetails";
    public static final String CLASS_HOMEPAGE = "sample.naif.com.nauss2.activity.HomePage";
    public static final String CLASS_LOGIN = "sample.naif.com.nauss2.InputLayoutLogIn.ILLogInInput";
    public static final String CLASS_COMPLAIN = "sample.naif.com.nauss2.makeComplains.MakeComplain";
    public static final String CLASS_COMPLAINS_LIST = "sample.naif.com.nauss2.oldComplainsList.ComplainList";
    public static final String CLASS_USERMANUAL = "sample.naif.com.nauss2.activity.HowItWorks";
    public static final String CLASS_CHANGELANGUGAE = "sample.naif.com.nauss2.activity.ChangeLanguage";
    public static final String CLASS_NOTIFICATION = "sample.naif.com.nauss2.notification.Notification";
    public static final String CLASS_FEEDBACK = "sample.naif.com.nauss2.feedback.FeedBack";
    public static final String CLASS_CHANGEPASSWORD = "sample.naif.com.nauss2.changePassword.ChangePassword";
    public static final String CLASS_USERPROFILE = "sample.naif.com.nauss2.userProfile.UserProfile";
    public static final String LIST_PENDING = "[{\"complain_id\":6,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":5,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":4,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":3,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":1,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":2,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"}]";
    public static final String LIST_PROGRESS = "[{\"complain_id\":6,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":5,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model2.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":4,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model3.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":3,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_21122016.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":1,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_05012017.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":2,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_08012017.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":7,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_27122016_3.jpg\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"}]";
    public static final String LIST_COMPLETED = "[{\"complain_id\":3,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_21122016.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":1,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_05012017.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":2,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_08012017.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":7,\"img\":\"http://nauss.edu.sa//Ar/News/UniversityNews/PublishingImages/news_27122016_3.jpg\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":5,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model2.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":4,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model3.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"},{\"complain_id\":6,\"img\":\"http://nauss.edu.sa/_layouts/images/nauss2013/en/model1.png\",\"title\":\"keyboard is now working properly.\",\"description\":\"issue in computer at 3rd floor development center etc\",\"time\":\"1-Rajab-1438\"}]";
    public static final String LIST_FEEDBACK = "[{\"complain_id\":\"A123XXX001\",\"title\":\"keyboard is now working properly.\",\"requested_date\":\"1-Rajab-1438\",\"requested_time\":\"8.00 AM\",\"work_status\":\"Completed\"},{\"complain_id\":\"A123XXX002\",\"title\":\"keyboard is now working properly.\",\"requested_date\":\"2-Rajab-1438\",\"requested_time\":\"8.00 AM\",\"work_status\":\"Completed\"},{\"complain_id\":\"A123XXX003\",\"title\":\"keyboard is now working properly.\",\"requested_date\":\"3-Rajab-1438\",\"requested_time\":\"8.00 AM\",\"work_status\":\"Completed\"},{\"complain_id\":\"A123XXX004\",\"title\":\"keyboard is now working properly.\",\"requested_date\":\"4-Rajab-1438\",\"requested_time\":\"8.00 AM\",\"work_status\":\"Completed\"},{\"complain_id\":\"A123XXX005\",\"title\":\"keyboard is now working properly.\",\"requested_date\":\"5-Rajab-1438\",\"requested_time\":\"8.00 AM\",\"work_status\":\"Completed\"},{\"complain_id\":\"A123XXX006\",\"title\":\"keyboard is now working properly.\",\"requested_date\":\"6-Rajab-1438\",\"requested_time\":\"8.00 AM\",\"work_status\":\"Completed\"}]";

    public static void savePreferencesToken(String Key, String value, Context context) {
        SharedPreferences sharedPreferences = context.getSharedPreferences("MyPref", 0);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putString(Key, value);
        String temp = "Key :" + Key + ">>>>>>>> Value " + value;
        Log.d("Constants ", "Share Data " + temp);
        editor.commit();

    }

    public static String loadSavedPreferenceToken(String Key, Context context) {
        SharedPreferences sharedPreferences = context.getSharedPreferences("MyPref", 0);
        String Value = sharedPreferences.getString(Key, "");
        return Value;

    }
}
